# Generated by Django 6.0.3 on 2026-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_audiochef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dishTypes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='extendedIngredients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='readyInMinutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
